### ISSUE TITLE
Unicode Error

### ISSUE THREAD

**Issue by animosity022** [sharkykh/TraktPlaybackProgressManager#1]
This works great as I removed a ton of errors from my list. If I remove the auth file and redo it works great, but if I try to relaunch it, I get the following error:

![image](https://user-images.githubusercontent.com/5088712/43003735-804d80cc-8bfb-11e8-844f-2524dcccb948.png)

**Comment by sharkykh** [comment]
Hey @animosity22
I can't see the error in the image.
I have pushed a new version though. could you try it and see if the issue persists?

**Comment by animosity022** [comment]
Hmm. I grabbed that version and it seems to die once I auth via my PIN for Trakt.

<img width="996" alt="image" src="https://user-images.githubusercontent.com/5088712/43017938-e6480044-8c25-11e8-8367-9891f531bd40.png">

**Comment by sharkykh** [comment]
Ok, removed the icon I added in the latest version.
Can you try the latest commit?

**Comment by animosity022** [comment]
Closer, I can start it up now, but I've got so many things, it is bigger than the screen. I'm trying to see if I can the side bars to pop up as I run through VNC on my box.

**Comment by sharkykh** [comment]
Oh, I can see the issue with the list box getting too big instead of having scroll bars. I'll try to fix that.

**Comment by sharkykh** [comment]
Hopefully I fixed it the list overflowing now. It should have a scrollbar.

**Comment by animosity022** [comment]
Sweet. Working superb. Thanks for the quick fix!
