### ISSUE TITLE
doesn't seem to retrieve all TV shows

### ISSUE THREAD

**Issue by trevevs** [sharkykh/TraktPlaybackProgressManager#11]
awesome app- just what I was lookin for... it gets a lot of my progress, but lots are missing too..

**Comment by sharkykh** [comment]
I have not encountered that.
Furthermore, I believe the code is getting everything the connected Trakt profile has saved, so I can't change anything to get any more.

Just to be sure, you understand playback progress (scrobbles that were paused or stopped midway) is not the same as the [watch progress on Trakt.tv](https://trakt.tv/users/me/progress)?

**Comment by trevevs** [comment]
yes my bad - watch progress is what I was needing nuked.  This a possibility for future?

**Comment by sharkykh** [comment]
No, I do not plan to extend this app's functionality to manage any other aspects.

If you want to remove shows from your watch history, as far as I know your options are:

Go to [show watch history](https://trakt.tv/users/me/history/shows/added) and click the purple ☑️, then "All episode plays" on each show you'd like to remove from your history. Same goes for movies - ([movie watch history](https://trakt.tv/users/me/history/movies/added)).
TIP: Click "Toggle Dividers" for a better view. 
![3e1m7IzPFS](https://user-images.githubusercontent.com/10238474/145729409-9e20c3d6-c4dd-4935-aa84-457e6e53e4be.gif)

Or use [TraktRater](https://github.com/damienhaynes/TraktRater), I believe they have a maintenance option where you can remove different types of data in bulk (all watched episodes, all watched movies, etc.), but you might not be able to pick and choose.
