### ISSUE TITLE
Help with install/ Use for Android kodi install

### ISSUE THREAD

**Issue by phatboyj** [sharkykh/TraktPlaybackProgressManager#9]
@sharkykh
I read the ReadMe but I am still clueless I need Help with in[stall/ Use for Android kodi install.  I can use in windows if necessary I just need more detailed instructions as I have no idea what pip -r anything means

Also I know where to find the specific Labels but how do I add say the [" help wanted "](https://github.com/sharkykh/TraktPlaybackProgressManager/issues?q=is%3Aopen+is%3Aissue) Label to the subject of my Issue?
 
Thanks in Advance

**Comment by sharkykh** [comment]
Okay, so first off, I didn't make this with mobile platforms in mind (see #5), so I don't think it would be possible to run this on a mobile device.

About installing it on Windows (or any other desktop platform for that matter), you need to [install Python first](https://www.python.org/downloads/release/python-373/#files).
The Windows installation comes with the `pip` tool which is used for downloading and installing Python packages/modules.
After you install Python on your machine, `pip` should be available in command prompt and you can follow the "readme" instructions.
Let me know if you need more help.

**Comment by phatboyj** [comment]
@sharkykh
Thanks For the detailed instructions I had read the comment about mobile application and gave it a thumbs up
As far as the labels? Can they not be added by the user posting the issue?

**Comment by sharkykh** [comment]
> As far as the labels? Can they not be added by the user posting the issue?

That's correct. That's just the way GitHub works - only repository owners and/or members can add or remove labels.

**Comment by phatboyj** [comment]
Thanks for clarifying you've been a great help!

**Comment by phatboyj** [comment]
@sharkykh
                   All was good until

```
Installing collected packages: six, python-dateutil, arrow, urllib3, idna, chardet, certifi, requests, trakt.py
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: 'c:\\program files\\python37\\Lib\\site-packages\\six.py'
Consider using the `--user` option or check the permissions.
```
Any help would be Great, I'm New to Python.

**Comment by sharkykh** [comment]
It doesn't have permissions because you installed in `Program Files`.
If you use an an administrator command prompt instead, it should be fine:
<kbd>Windows Key</kbd>+<kbd>R</kbd> -> `cmd` -> <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Enter</kbd>

**Comment by phatboyj** [comment]
Do I need to cd to the folder I have your files dwlded to or is there a way to start cmd in admin in the proper folder I have a cmd shorcut on my desktop if that helps  but I don't know how to start it in the nesc dir. with Admin Do You?

**Comment by sharkykh** [comment]
I don't know of a way to start an elevated `cmd` in a specific folder.
But you can use something like `cmd /K cd "C:\Dev\TraktPlaybackProgressManager"` instead of just `cmd` (and change the path)

**Comment by phatboyj** [comment]
So the /k is the arg for admin? 
and I still use the ctrl+shift+enter after correct?

Sorry I don't know the syntax to do the buttons like you did!

I had already just CD'ed into it before your comment and it's running,  however after the auth pin I got a pop-up saying successful but the bottom of the gui still says not logged in but I hit refresh and it populated with over 150 entries so it seems to be working in spite of it saying not- logged in on the bottom left

**Comment by sharkykh** [comment]
> So the /k is the arg for admin?

It just means it runs the command after it and leaves the `cmd` window open
`/K      Carries out the command specified by string but remains`

> and I still use the ctrl+shift+enter after correct?

Yes

> I had already just CD'ed into it before your comment and it's running, however after the auth pin I got a pop-up saying successful but the bottom of the gui still says not logged in but it seems to be working in spite of that

What happens if you exit the app and run it again? It should say "logged in" after that.
If not, then maybe it doesn't have permission to write the file.
Did you put the application code in `Program Files` too? (you shouldn't)

**Comment by phatboyj** [comment]
So do I run the /k in the cmd window or in the run dialog after Win+r   "I only asked because you said something about having the cmd already open or leaving it running"

Actually I just tried to run it again as you suggested and it flashes the Gui for a split second and then disappears.

And to answer your last? 
No, your package folder is on my desktop.

**Comment by sharkykh** [comment]
In the run window.
<kbd>Windows Key</kbd>+<kbd>R</kbd> -> `cmd /K cd "C:\Dev\TraktPlaybackProgressManager"` -> <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Enter</kbd>

> Actually I just tried to run it again as you suggested and it flashes the Gui for a split second and then disappears.

Hmm, sounds like a bug.
Can you try running `python main.pyw` on a command prompt in the package folder?
It should print some information about the issue.

**Comment by phatboyj** [comment]
yeah but I may need some more guidance Do I simply type python main.pyw and hit enter from the Cd'ed dir

**Comment by sharkykh** [comment]
Yes

**Comment by phatboyj** [comment]
```
C:\WINDOWS\system32>cd C:\Users\Hailey\Desktop\TraktPlaybackProgressManager-0.7

C:\Users\Hailey\Desktop\TraktPlaybackProgressManager-0.7>python main.pyw
Traceback (most recent call last):
  File "main.pyw", line 11, in <module>
    main()
  File "C:\Users\Hailey\Desktop\TraktPlaybackProgressManager-0.7\tppm\__init__.py", line 442, in main
    root.main()
  File "C:\Users\Hailey\Desktop\TraktPlaybackProgressManager-0.7\tppm\__init__.py", line 230, in main
    self.update_user_info()
  File "C:\Users\Hailey\Desktop\TraktPlaybackProgressManager-0.7\tppm\__init__.py", line 403, in update_user_info
    text += ' ({1})'.format(self.fullname)
IndexError: tuple index out of range

C:\Users\Hailey\Desktop\TraktPlaybackProgressManager-0.7>
```

**Comment by sharkykh** [comment]
Thank you, very helpful!
I just updated the code, you can re-download it and try again.

**Comment by phatboyj** [comment]
It's I who's Grateful Dwldng now I'll let you know

**Comment by phatboyj** [comment]
@sharkykh  "You Are The Man!"

I Dwlded the master.zip  ran it the first time via cmd python main.pyw  it ran as expected, asked for pin auth, it was successful And the Gui bottom left stated I was logged in as ME  foud 197 entries "that how bad I needed your App" ,  I then closed it out an ran it again by double clicking the main.pyw file and the result were again the same and as expected.

Again,  @sharkykh  "You Are The Man!"   197 entries about to disappear into the either!  "Hells Yeah"

Your extremely elated friend phatboyj
